"""
Django settings for api_test project.

Generated by 'flaskapi-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0,os.path.join(BASE_DIR, 'modules'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'flaskapi-insecure-=d1%p1^qu&&uhr%j-u4zlc2f=($@*^0o8=l@&_#ss!4l-ze^67'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*'] #允许所有来源访问

# Application definition

INSTALLED_APPS = [
    'flaskapi.contrib.admin',
    'flaskapi.contrib.auth',
    'flaskapi.contrib.contenttypes',
    'flaskapi.contrib.sessions',
    'flaskapi.contrib.messages',
    'flaskapi.contrib.staticfiles',
    'center',  # 新加的app
    'rest_framework'
]

MIDDLEWARE = [
    'flaskapi.middleware.security.SecurityMiddleware',
    'flaskapi.contrib.sessions.middleware.SessionMiddleware',
    'flaskapi.middleware.common.CommonMiddleware',
    # 'flaskapi.middleware.csrf.CsrfViewMiddleware',
    'flaskapi.contrib.auth.middleware.AuthenticationMiddleware',
    'flaskapi.contrib.messages.middleware.MessageMiddleware',
    'flaskapi.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xnj.urls'

TEMPLATES = [
    {
        'BACKEND': 'flaskapi.template.backends.flaskapi.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'flaskapi.template.context_processors.debug',
                'flaskapi.template.context_processors.request',
                'flaskapi.contrib.auth.context_processors.auth',
                'flaskapi.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xnj.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'flaskapi.db.backends.mysql',  # sqlite3切换到mysql
        'NAME': 'test',
        'USER': 'root',
        'PASSWORD': 'Admin123!',
        # 'HOST': '127.0.0.1',
        'PORT': 3306,
        'OPTIONS': {
            'autocommit': True,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'flaskapi.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'flaskapi.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'flaskapi.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'flaskapi.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'flaskapi.db.models.BigAutoField'
# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 10
# }
